=== visualizedata/archive/data/keynotes/_schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "type": "object",
  "required": [],
  "additionalProperties": false,
  "properties": {
    "year": {
      "type": "integer"
    },
    "title": {
      "type": "string"
    },
    "department": {
      "type": "string"
    },
    "description": {
      "type": "string"
    },
    "location": {
      "type": "string"
    },
    "date": {
      "type": "string"
    },
    "time": {
      "type": "string"
    },
    "url": {
      "type": "string",
      "pattern": "(^(http|https)|^$)"
    },
    "students": {
      "type": "array",
      "items": {
        "type": "string"
      }
    },
    "video_source_url": {
      "type": "string",
      "pattern": "(^(http|https)|^$)"
    },
    "video_embed_html": {
      "type": "string"
    }
  }
}

=== visualizedata/archive/src/data/keynotes/2026.json
{
  "year": 2026,
  "title": "2026 Keynotes",
  "department": "MS Data Visualization",
  "description": "",

  "location": "",
  "date": "",
  "time": "",
  "url": "",

  "students": [
    "Neven Armanios",
    "Olivia Kasmin",
    "Saehun Kim",
    "Sofia Molina",
    "Nichos Molnar",
    "Maggie Navracruz",
    "LuisPablo Padres",
    "Derin Savasan",
    "Lara Yeyati Preiss"
  ],
  "video_embed_html": "<iframe src=\"https://player.vimeo.com/video/1194770381?badge=0&amp;autopause=0&amp;player_id=0&amp;app_id=58479\" frameborder=\"0\" allow=\"autoplay; fullscreen; picture-in-picture; clipboard-write; encrypted-media; web-share\" referrerpolicy=\"strict-origin-when-cross-origin\" title=\"2025 MS Data Visualization Keynotes | Parsons at The New School\"></iframe>"
}

=== visualizedata/archive/data/keynotes/2021.json
{
  "year": 2021,
  "title": "2021 Keynotes",
  "department": "MS Data Visualization",
  "description": "",

  "location": "Online",
  "date": "",
  "time": "",
  "url": "",

  "students": [],
  "video_source_url": "https://player.vimeo.com/video/545201647",
  "video_embed_html": "<iframe src=\"https://player.vimeo.com/video/545201647\" width=\"640\" height=\"360\" frameborder=\"0\" allow=\"autoplay; fullscreen; picture-in-picture\" allowfullscreen></iframe>"
}

=== visualizedata/archive/data/keynotes/2020.json
{
  "year": 2020,
  "title": "2020 Keynotes",
  "department": "MS Data Visualization",
  "description": "",

  "location": "Online",
  "date": "",
  "time": "",
  "url": "",

  "students": [
    "Marisa Asari",
    "Robin Coenen",
    "Mio Akasako",
    "Saloni Naishad Shah",
    "Michael Desai",
    "Dan Ran",
    "Amanda Anderson-You",
    "Yiran Ni",
    "Nour Zein",
    "Zui Chen",
    "Neil Oliver",
    "Lulu Tanenbaum",
    "Antonie Dreyer",
    "Janice Yamanaka-Lew",
    "Brad MacDonald",
    "John Outwater",
    "Caitlyn Ralph",
    "Daniel Grunenbaum",
    "Xingwei Huang"
  ],
  "video_source_url": "https://www.youtube.com/watch?v=Q97Bl3aiECs",
  "video_embed_html": "<iframe width=\"560\" height=\"315\" src=\"https://www.youtube.com/embed/Q97Bl3aiECs\" title=\"YouTube video player\" frameborder=\"0\" allow=\"accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture\" allowfullscreen></iframe>"
}

=== visualizedata/archive/src/data/keynotes/2025.json
{
  "year": 2025,
  "title": "2025 Keynotes",
  "department": "MS Data Visualization",
  "description": "",

  "location": "",
  "date": "",
  "time": "",
  "url": "",

  "students": [
    "Lisa Quinley",
    "Tak Watanabe",
    "Josh Strupp",
    "Bella Kwon",
    "Daia Bromberg",
    "Monsicha Srisuantang",
    "Xuan Tan",
    "Harshita Chakravadhanula",
    "Nour Al Safadi",
    "Katherine Chui",
    "Annie Lee",
    "Ian Yu",
    "Eva Lucy Alvarado",
    "Livia Ramos",
    "Sani Sharma",
    "Ani Matevosian",
    "Sophie Graves",
    "Steph Wu"
  ],
  "video_embed_html": "<iframe src=\"https://player.vimeo.com/video/1102333444?badge=0&amp;autopause=0&amp;player_id=0&amp;app_id=58479\" frameborder=\"0\" allow=\"autoplay; fullscreen; picture-in-picture; clipboard-write; encrypted-media; web-share\" referrerpolicy=\"strict-origin-when-cross-origin\" title=\"2025 MS Data Visualization Keynotes | Parsons at The New School\"></iframe>"
}

=== visualizedata/archive/data/keynotes/2022.json
{
  "year": 2022,
  "title": "2022 Keynotes",
  "department": "MS Data Visualization",
  "description": "",

  "location": "Online",
  "date": "2022-05-18",
  "time": "5:00PM",
  "url": "",

  "students": [
    "Molly Cook",
    "Juliet Craig",
    "Gísli Gudjónsson",
    "Jiahui(Jessie) Han",
    "Yann Kerblat",
    "Yoana Kosturska",
    "Baihan Lin",
    "Wenqin Lu",
    "Shea Molloy",
    "Omar Nema",
    "Jeremy Odell",
    "Kasey Zhuravlev"
  ],
 "video_source_url": "https://github.com/visualizedata/archive/raw/main/app/assets/media/2022keynotes.mp4",
 "video_embed_html": "<video autoplay controls muted preload='auto' src='https://github.com/visualizedata/archive/raw/main/app/assets/media/2022keynotes.mp4'></video>"
}

=== visualizedata/archive/data/keynotes/2023.json
{
  "year": 2023,
  "title": "2023 Keynotes",
  "department": "MS Data Visualization",
  "description": "",
  "location": "",
  "date": "2023-05-17",
  "time": "6:00PM",
  "url": "",
  "students": [
    "Isabel Bonnet",
    "Stephanie Dang",
    "Angelica Hom",
    "Zora Wan",
    "Hao Lun Hung",
    "Tatiana Lahera Kalainoff",
    "Asad Ahmad Khan",
    "Jooyoung Lee",
    "Tina Titus Mathew",
    "Huong Pham",
    "Alix Maissa Scherer",
    "Ladfah Suwichacherdchu",
    "Chay Thawaranont",
    "Tanishia Williams",
    "Shuyao Xiao"
  ],
  "video_source_url": "",
  "video_embed_html": ""
}
